### ISSUE TITLE
Error parsing Vaisala file

### ISSUE THREAD

**Issue by kinow** [kinow/pccora#5]
One of the radiosonde data files from Lauder failed to process with the current parser and convert2netcdf script.

```
Traceback (most recent call last):
  File "directory_batch_convert.py", line 43, in <module>
    main()
  File "directory_batch_convert.py", line 39, in main
    parseandconvert(input_file, output_file)
  File "/home/kinoshitabd/Development/python/workspace/pccora/scripts/convert2netcdf4.py", line 14, in parseandconvert
    pccora_parser.parse_file(input)
  File "/home/kinoshitabd/Development/python/workspace/pccora/scripts/../pccora/pccora.py", line 339, in parse_file
    self.result = pccora_file.parse_stream(fid)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/home/kinoshitabd/Development/python/workspace/pccora/scripts/../pccora/pccora.py", line 13, in <lambda>
    decoder = lambda obj, ctx: obj.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 2: invalid start byte

```

**Comment by kinow** [comment]
File name: 96020409.nc

**Comment by kinow** [comment]
There are other (100?) files that failed. Logs in work computer (note to self: transfer them to somewhere to keep track of it)

**Comment by kinow** [comment]
Actually 1086 files failed.

**Comment by kinow** [comment]
```
Traceback (most recent call last):
  File "convert2netcdf4.py", line 370, in <module>
    main()
  File "convert2netcdf4.py", line 367, in main
    parseandconvert(file, output)
  File "convert2netcdf4.py", line 15, in parseandconvert
    pccora_parser.parse_file(input)
  File "../pccora/pccora.py", line 339, in parse_file
    self.result = pccora_file.parse_stream(fid)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 328, in _parse
    return _read_stream(stream, self.length)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/site-packages/construct/core.py", line 305, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
```

**Comment by kinow** [comment]
For the error above, turns out the file in question actually had 0 bytes.

**Comment by kinow** [comment]
And for other files, even though the header said it would have X hires data entries, it could have less Y entries.

**Comment by kinow** [comment]
In one file, 00022922, it is failing because:

- the month is 02
- the day is 29
- but the year was being set to 3900

**Comment by kinow** [comment]
The file 97020309.edt, even though it is said in the specification that the data field always contain 25 entries, didn't have 25 lines.

Fixed it by removing the minimum number, setting it to 1, and leaving the maximum to 25.

**Comment by kinow** [comment]
`The first 25 data records in an EDT file are always reserved for standard level data. The standard levels are sorted according to ascending height. The 26th data record contains ground level data. The rest of the levels are sorted according to ascending height.`

**Comment by kinow** [comment]
The file 14091423.06E has issues with the month value: `month must be in 1..12`

**Comment by kinow** [comment]
The data inside the  file is quite bad:

```
Container:
    station_type = 0
    region_number = 128
    wmo_block_number = -32384
    wmo_station_number = -7867
    station_latitude = -94.09
    station_longitude = 2.64
    station_altitude = 0
    wind_speed_unit = 128
    telecommunications_headings = 21888
    reserved = 7898
    sounding_type = 32258
    start_mode = 263
    time_elapsed = 0
    ptu_rate = 128
    spu_serial_number = 8388736
    year = 2028
    month = 128
    day = 128
    julian_date = 0
    hour = 0
    minute = 128
    message_year = -32368
    message_month = -9403
    message_day = -9409
    message_hour = 264
    cloud_group = '\x00\x00\x00_'
    weather_group = '\x1d\x02~\x07\x01'
    napp = '\x00\x00\x00\x00'
    surface_pressure = 12.8
    surface_temperature = 12.8
    surface_humidity = 128
    surface_wind_direction = 128
    surface_wind_speed = 0
    radiosonde_number = '\x00\x00\x00E?'
    sounding_number = '\x08\x01\x00\x00\x00i\x1c'
    pressure_correction = 3225.8
    temperature_correction = 26.3
    humidity_correction = 0
    success_of_signal = 128
    pressure_accept_level = 128
    pressure_replace_level = 128
    pressure_reject_level = 128
    temperature_accept_level = 128
    temperature_replace_level = 128
    temperature_reject_level = 0
    humidity_accept_level = 0
    humidity_replace_level = 128
    humidity_reject_level = -32336
    total_omega_count = -12475
    reason_temination = -8897
    omega_count = b'\x08\x01\x00\x00\x80\x00\x80r\xda\x1b\x02\x80\x07\x01\x00\x00\x80\x00\x80\x00\x80\x00'
    wind_computing_mode = 128
    wind_mode = 128
    stations_used = 128
    loranc_chains_used = 0
    gri_chain_1 = 0
    gri_chain_2 = -32768
    exclude_loran_transmitters = -16384
    phase_integration_time = 129
    phase_integration_time_1 = -14011
    phase_integration_time_2 = -8897
    phase_integration_time_3 = 264
    phase_integration_time_4 = 0
    phase_integration_time_5 = 128
    phase_integration_time_6 = 31872
    phase_integration_change_level_1 = 7130
    phase_integration_change_level_2 = -32766
    phase_integration_change_level_3 = 263
    phase_integration_change_level_4 = 0
    phase_integration_change_level_5 = 128
    phase_integration_change_level_6 = 128
    reference_pressure = 12.8
    reference_temperature = 12.8
    reference_humidity = 128
```
So it is probably better to discard this file.

**Comment by kinow** [comment]
These are the current stats now for Invercargill.

```
2016-06-30 21:48:30,797 ### Stats ###
2016-06-30 21:48:30,797 - TOTAL   13851
2016-06-30 21:48:30,797 - OK      13815
2016-06-30 21:48:30,797 - NOK     16
2016-06-30 21:48:30,797 - SKIPPED 20
```

**Comment by kinow** [comment]
The remaining 15 files failed due to the syspar field.

This field is supposed to always have 8087 bytes.

The problem in this case is that we can't greedily parse as many bytes as we find, since that would consume the whole input stream.

Tis not impossible to find out what's causing these 15 errors, but would require more time.

**Comment by kinow** [comment]
The other files that are failing to parse, in the raw data, contain weird values. In most of them the SYSPAR is shorter than 8087 bytes.

So these entries can be discarded. Closing the ticket.
